# Generated by Django 2.2 on 2020-06-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('role_id', models.IntegerField()),
            ],
            options={
                'db_table': 'user_role',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'managed': False},
        ),
    ]
